name: proto_project_lamp_drupal
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php_2
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache_2
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "${MYSQL_PROT}:3306"
    volumes:
            - data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql_2
networks:
  frontend:
  backend:
volumes:
    data:
